import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        brand: {
          bg: "#0B0D11",
          surface: "#13151B",
          "surface-hover": "#1A1D26",
          border: "#23262F",
          "border-hover": "#2E323D",
          text: "#E8EAED",
          "text-secondary": "#9BA1AD",
          "text-tertiary": "#5F6571",
          accent: "#3B82F6",
          "accent-hover": "#2563EB",
          "accent-muted": "#1E3A5F",
          success: "#22C55E",
          "success-muted": "#14532D",
          warning: "#F59E0B",
          "warning-muted": "#422006",
          critical: "#EF4444",
          "critical-muted": "#450A0A",
          // Keep legacy alias for backward compat
          "text-muted": "#9BA1AD",
        },
        light: {
          bg: "#FFFFFF",
          surface: "#F9FAFB",
          "surface-hover": "#F3F4F6",
          border: "#E5E7EB",
          "border-hover": "#D1D5DB",
          text: "#111827",
          "text-secondary": "#4B5563",
          "text-tertiary": "#9CA3AF",
          accent: "#2563EB",
          "accent-hover": "#1D4ED8",
          "accent-muted": "#DBEAFE",
          success: "#16A34A",
          "success-muted": "#DCFCE7",
          warning: "#D97706",
          "warning-muted": "#FEF3C7",
          critical: "#DC2626",
          "critical-muted": "#FEE2E2",
        },
        ecosystem: {
          forest: "#1a4731",
          "forest-border": "#2d6b4f",
          swamp: "#2d3a1f",
          "swamp-border": "#4a5a2f",
          desert: "#8b7355",
          "desert-border": "#a6896a",
          seedbed: "#2d5a27",
          "seedbed-border": "#3d7a34",
          meadow: "#3d6b3d",
          "meadow-border": "#4d8b4d",
        },
        role: {
          pillar: "#22c55e",
          supporter: "#3b82f6",
          competitor: "#f97316",
          dead: "#6b7280",
        },
        severity: {
          critical: "#ef4444",
          high: "#f97316",
          medium: "#eab308",
          low: "#6b7280",
        },
      },
      fontFamily: {
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "SFMono-Regular", "monospace"],
      },
      spacing: {
        "0.5": "4px",
        "1": "8px",
        "1.5": "12px",
        "2": "16px",
        "2.5": "20px",
        "3": "24px",
        "4": "32px",
        "5": "40px",
        "6": "48px",
        "8": "64px",
        "10": "80px",
        "12": "96px",
      },
      borderRadius: {
        card: "12px",
        button: "8px",
        input: "8px",
        badge: "6px",
      },
      maxWidth: {
        content: "1200px",
      },
      width: {
        sidebar: "240px",
        "sidebar-collapsed": "64px",
      },
      animation: {
        "toast-in": "slideInRight var(--timing-normal, 200ms) ease-out",
        "toast-out": "slideOutRight var(--timing-normal, 200ms) ease-in forwards",
      },
      keyframes: {
        slideInRight: {
          from: { transform: "translateX(100%)", opacity: "0" },
          to: { transform: "translateX(0)", opacity: "1" },
        },
        slideOutRight: {
          from: { transform: "translateX(0)", opacity: "1" },
          to: { transform: "translateX(100%)", opacity: "0" },
        },
      },
      transitionDuration: {
        fast: "100ms",
        normal: "200ms",
        smooth: "300ms",
        deliberate: "500ms",
      },
    },
  },
  plugins: [],
};
export default config;
