module.exports = {
  apps: [
    {
      name: 'enough-backend',
      cwd: '/home/ubuntu/Projects/enough/backend',
      script: 'python3',
      args: '-m uvicorn app.main:app --host 0.0.0.0 --port 8000',
      interpreter: 'none',
      env_file: '/home/ubuntu/Projects/enough/backend/.env',
      autorestart: true,
      watch: false,
      max_memory_restart: '800M',
      error_file: '/home/ubuntu/Projects/enough/logs/backend-error.log',
      out_file:   '/home/ubuntu/Projects/enough/logs/backend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'enough-frontend',
      cwd: '/home/ubuntu/Projects/enough/frontend',
      script: 'node_modules/.bin/next',
      args: 'start -p 3000',
      interpreter: 'none',
      autorestart: true,
      watch: false,
      max_memory_restart: '600M',
      error_file: '/home/ubuntu/Projects/enough/logs/frontend-error.log',
      out_file:   '/home/ubuntu/Projects/enough/logs/frontend-out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
    },
    {
      name: 'enough-tunnel-be',
      script: '/home/ubuntu/bin/cloudflared',
      args: 'tunnel --url http://localhost:8000',
      interpreter: 'none',
      autorestart: true,
      watch: false,
      error_file: '/home/ubuntu/Projects/enough/logs/tunnel-be-error.log',
      out_file:   '/home/ubuntu/Projects/enough/logs/tunnel-be-out.log',
    },
    {
      name: 'enough-tunnel-fe',
      script: '/home/ubuntu/bin/cloudflared',
      args: 'tunnel --url http://localhost:3000',
      interpreter: 'none',
      autorestart: true,
      watch: false,
      error_file: '/home/ubuntu/Projects/enough/logs/tunnel-fe-error.log',
      out_file:   '/home/ubuntu/Projects/enough/logs/tunnel-fe-out.log',
    },
  ],
};
