"""Position monitoring — detect ranking drops, gains, and new competitors.

Compares current GSC position data against 7-day baseline to generate
alerts for significant position changes. Designed to run during the
daily analytics refresh cycle.
"""

import logging
from datetime import datetime, timezone, timedelta
from uuid import UUID

import asyncpg

logger = logging.getLogger(__name__)


class PositionMonitor:
    """Monitor GSC position changes and generate alerts."""

    POSITION_DROP_THRESHOLD = 3  # positions dropped to trigger alert
    POSITION_GAIN_THRESHOLD = 3  # positions gained to trigger alert

    async def check_position_changes(
        self, db: asyncpg.Connection, site_id: UUID
    ) -> dict[str, int]:
        """Compare current vs 7-day-ago positions, generate alerts.

        Returns counts of alerts generated by type.
        """
        now = datetime.now(timezone.utc)
        counts = {"position_drop": 0, "position_gain": 0}

        # Get current avg positions (last 3 days) vs baseline (8-14 days ago)
        rows = await db.fetch(
            """
            WITH current_pos AS (
                SELECT gs.post_id, gs.query,
                       AVG(gs.avg_position) AS current_position,
                       SUM(gs.clicks) AS current_clicks
                FROM gsc_metrics gs
                JOIN posts p ON p.id = gs.post_id
                WHERE p.site_id = $1
                  AND gs.date >= CURRENT_DATE - 3
                GROUP BY gs.post_id, gs.query
            ),
            baseline_pos AS (
                SELECT gs.post_id, gs.query,
                       AVG(gs.avg_position) AS baseline_position
                FROM gsc_metrics gs
                JOIN posts p ON p.id = gs.post_id
                WHERE p.site_id = $1
                  AND gs.date BETWEEN CURRENT_DATE - 14 AND CURRENT_DATE - 8
                GROUP BY gs.post_id, gs.query
            )
            SELECT c.post_id, c.query, c.current_position, c.current_clicks,
                   b.baseline_position,
                   (c.current_position - b.baseline_position) AS position_change
            FROM current_pos c
            JOIN baseline_pos b ON c.post_id = b.post_id AND c.query = b.query
            WHERE ABS(c.current_position - b.baseline_position) >= $2
            ORDER BY ABS(c.current_position - b.baseline_position) DESC
            LIMIT 50
            """,
            site_id,
            float(self.POSITION_DROP_THRESHOLD),
        )

        for row in rows:
            change = row["position_change"]
            if change > 0:
                # Position number went up = ranking dropped
                alert_type = "position_drop"
                counts["position_drop"] += 1
            else:
                alert_type = "position_gain"
                counts["position_gain"] += 1

            # Avoid duplicate alerts for same post+keyword within 7 days
            existing = await db.fetchval(
                """
                SELECT id FROM position_alerts
                WHERE site_id = $1 AND post_id = $2 AND keyword = $3
                  AND alert_type = $4
                  AND detected_at > NOW() - INTERVAL '7 days'
                """,
                site_id,
                row["post_id"],
                row["query"],
                alert_type,
            )
            if existing:
                continue

            await db.execute(
                """
                INSERT INTO position_alerts
                    (site_id, post_id, alert_type, keyword,
                     old_position, new_position, details, detected_at)
                VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
                """,
                site_id,
                row["post_id"],
                alert_type,
                row["query"],
                row["baseline_position"],
                row["current_position"],
                {
                    "change": round(change, 1),
                    "current_clicks": row["current_clicks"],
                },
                now,
            )

        logger.info(
            "Position monitor for site %s: %d drops, %d gains",
            site_id,
            counts["position_drop"],
            counts["position_gain"],
        )
        return counts

    async def get_alerts(
        self,
        db: asyncpg.Connection,
        site_id: UUID,
        *,
        status: str | None = None,
        limit: int = 50,
    ) -> list[dict]:
        """Get recent position alerts for a site."""
        conditions = ["pa.site_id = $1"]
        params: list = [site_id]
        idx = 2

        if status:
            conditions.append(f"pa.status = ${idx}")
            params.append(status)
            idx += 1

        params.append(limit)

        rows = await db.fetch(
            f"""
            SELECT pa.id, pa.site_id, pa.post_id, pa.alert_type,
                   pa.keyword, pa.old_position, pa.new_position,
                   pa.details, pa.status, pa.detected_at,
                   p.title AS post_title, p.url AS post_url
            FROM position_alerts pa
            LEFT JOIN posts p ON p.id = pa.post_id
            WHERE {' AND '.join(conditions)}
            ORDER BY pa.detected_at DESC
            LIMIT ${idx}
            """,
            *params,
        )

        return [
            {
                "id": str(r["id"]),
                "site_id": str(r["site_id"]),
                "post_id": str(r["post_id"]) if r["post_id"] else None,
                "alert_type": r["alert_type"],
                "keyword": r["keyword"],
                "old_position": r["old_position"],
                "new_position": r["new_position"],
                "details": r["details"] or {},
                "status": r["status"],
                "detected_at": r["detected_at"].isoformat() if r["detected_at"] else None,
                "post_title": r["post_title"],
                "post_url": r["post_url"],
            }
            for r in rows
        ]

    async def get_alerts_since(
        self,
        db: asyncpg.Connection,
        site_id: UUID,
        since: datetime,
    ) -> list[dict]:
        """Get alerts created since a given timestamp."""
        rows = await db.fetch(
            """
            SELECT pa.id, pa.alert_type, pa.keyword,
                   pa.old_position, pa.new_position,
                   pa.details, pa.detected_at,
                   p.title AS post_title, p.url AS post_url
            FROM position_alerts pa
            LEFT JOIN posts p ON p.id = pa.post_id
            WHERE pa.site_id = $1 AND pa.detected_at > $2
            ORDER BY pa.detected_at DESC
            LIMIT 20
            """,
            site_id,
            since,
        )
        return [
            {
                "id": str(r["id"]),
                "alert_type": r["alert_type"],
                "keyword": r["keyword"],
                "old_position": r["old_position"],
                "new_position": r["new_position"],
                "details": r["details"] or {},
                "detected_at": r["detected_at"].isoformat() if r["detected_at"] else None,
                "post_title": r["post_title"],
                "post_url": r["post_url"],
            }
            for r in rows
        ]
