'use client';

import { useSWRFetch } from '@/lib/hooks/useSWRFetch';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Spinner } from '@/components/ui/Spinner';
import {
  User,
  TreePine,
  Sun,
  Sprout,
  FileStack,
  ArrowRightLeft,
  TrendingUp,
  Activity,
  Heart,
  Download,
} from 'lucide-react';
import type { StewardProfile } from '@/lib/types/phase5';

function StatCard({
  icon: Icon,
  label,
  value,
  color,
}: {
  icon: React.ElementType;
  label: string;
  value: string | number;
  color: string;
}) {
  return (
    <Card>
      <div className="flex items-center gap-3">
        <div
          className="flex h-10 w-10 items-center justify-center rounded-lg"
          style={{ backgroundColor: `${color}20` }}
        >
          <Icon size={20} style={{ color }} />
        </div>
        <div>
          <div className="text-xs text-brand-text-muted">{label}</div>
          <div className="text-lg font-bold text-brand-text">{value}</div>
        </div>
      </div>
    </Card>
  );
}

export default function ProfilePage() {
  const { data: profile, isLoading } = useSWRFetch<StewardProfile>(
    '/profile/steward'
  );

  const handleExport = () => {
    if (!profile) return;

    const lines = [
      'Content Steward — Performance Summary',
      '═'.repeat(45),
      '',
      `Member Since: ${profile.member_since}`,
      '',
      '── Ecosystem Impact ──',
      `Swamps Cleared: ${profile.swamps_cleared}`,
      `Deserts Revived: ${profile.deserts_revived}`,
      `Seedlings Planted: ${profile.seedlings_planted}`,
      '',
      '── Consolidation Work ──',
      `Posts Consolidated: ${profile.total_posts_consolidated}`,
      `Redirects Created: ${profile.total_redirects_created}`,
      `Estimated Traffic Recovered: ${profile.estimated_traffic_recovered.toLocaleString()} sessions`,
      '',
      '── Overall Improvement ──',
      `Health Score Change: ${profile.health_improvement >= 0 ? '+' : ''}${profile.health_improvement.toFixed(1)}`,
      `Efficiency Change: ${profile.efficiency_improvement >= 0 ? '+' : ''}${profile.efficiency_improvement.toFixed(1)}%`,
      '',
      '— Generated by Enough',
    ];

    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'steward-performance-review.txt';
    a.click();
    URL.revokeObjectURL(url);
  };

  if (isLoading) {
    return (
      <div className="flex justify-center py-20">
        <Spinner size="lg" />
      </div>
    );
  }

  if (!profile) {
    return (
      <div className="text-center py-20 text-brand-text-muted">
        <User size={48} className="mx-auto mb-4 opacity-50" />
        <p>Unable to load profile.</p>
      </div>
    );
  }

  return (
    <div className="space-y-6 max-w-3xl">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold text-brand-text">Steward Profile</h1>
          <p className="text-sm text-brand-text-muted mt-1">
            Your honest accounting as a content steward. Member since {profile.member_since}.
          </p>
        </div>
        <Button variant="secondary" size="sm" onClick={handleExport}>
          <Download size={14} />
          Export for Review
        </Button>
      </div>

      {/* Ecosystem Impact */}
      <div>
        <h2 className="text-xs font-medium text-brand-text-muted uppercase mb-3">
          Ecosystem Impact
        </h2>
        <div className="grid grid-cols-3 gap-4">
          <StatCard
            icon={TreePine}
            label="Swamps Cleared"
            value={profile.swamps_cleared}
            color="#22c55e"
          />
          <StatCard
            icon={Sun}
            label="Deserts Revived"
            value={profile.deserts_revived}
            color="#eab308"
          />
          <StatCard
            icon={Sprout}
            label="Seedlings Planted"
            value={profile.seedlings_planted}
            color="#3b82f6"
          />
        </div>
      </div>

      {/* Consolidation Work */}
      <div>
        <h2 className="text-xs font-medium text-brand-text-muted uppercase mb-3">
          Consolidation Work
        </h2>
        <div className="grid grid-cols-3 gap-4">
          <StatCard
            icon={FileStack}
            label="Posts Consolidated"
            value={profile.total_posts_consolidated}
            color="#8b5cf6"
          />
          <StatCard
            icon={ArrowRightLeft}
            label="Redirects Created"
            value={profile.total_redirects_created}
            color="#f97316"
          />
          <StatCard
            icon={TrendingUp}
            label="Traffic Recovered"
            value={profile.estimated_traffic_recovered.toLocaleString()}
            color="#22c55e"
          />
        </div>
      </div>

      {/* Overall Improvement */}
      <div>
        <h2 className="text-xs font-medium text-brand-text-muted uppercase mb-3">
          Overall Improvement
        </h2>
        <div className="grid grid-cols-2 gap-4">
          <Card>
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-green-900/30">
                <Heart size={20} className="text-green-400" />
              </div>
              <div className="flex-1">
                <div className="text-xs text-brand-text-muted">Health Score Change</div>
                <div
                  className={`text-2xl font-bold ${
                    profile.health_improvement >= 0 ? 'text-green-400' : 'text-red-400'
                  }`}
                >
                  {profile.health_improvement >= 0 ? '+' : ''}
                  {profile.health_improvement.toFixed(1)}
                </div>
              </div>
            </div>
          </Card>
          <Card>
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-blue-900/30">
                <Activity size={20} className="text-blue-400" />
              </div>
              <div className="flex-1">
                <div className="text-xs text-brand-text-muted">Efficiency Change</div>
                <div
                  className={`text-2xl font-bold ${
                    profile.efficiency_improvement >= 0 ? 'text-green-400' : 'text-red-400'
                  }`}
                >
                  {profile.efficiency_improvement >= 0 ? '+' : ''}
                  {profile.efficiency_improvement.toFixed(1)}%
                </div>
              </div>
            </div>
          </Card>
        </div>
      </div>
    </div>
  );
}
